#1
SELECT ALUNO.nome
FROM ALUNO
JOIN DISCIPLINA_ALUNO ON ALUNO.codigo_aluno = DISCIPLINA_ALUNO.codigo_aluno
JOIN DISCIPLINA ON DISCIPLINA_ALUNO.codigo_disciplina = DISCIPLINA.codigo_disciplina
JOIN PROFESSOR_DISCIPLINA ON DISCIPLINA.codigo_disciplina = PROFESSOR_DISCIPLINA.codigo_disciplina
JOIN PROFESSOR ON PROFESSOR_DISCIPLINA.codigo_professor = PROFESSOR.codigo_professor
WHERE DISCIPLINA.nome = 'Cálculo' AND PROFESSOR.nome = 'João';

#2
SELECT DISCIPLINA.nome as disciplina, COUNT(ALUNO.codigo_aluno) as quantidade_alunos
FROM DISCIPLINA
LEFT JOIN DISCIPLINA_ALUNO ON DISCIPLINA.codigo_disciplina = DISCIPLINA_ALUNO.codigo_disciplina
LEFT JOIN ALUNO ON DISCIPLINA_ALUNO.codigo_aluno = ALUNO.codigo_aluno
GROUP BY DISCIPLINA.nome;

#3
SELECT DISCIPLINA.nome
FROM DISCIPLINA
WHERE NOT EXISTS (
    SELECT DISTINCT DISCIPLINA.codigo_disciplina
    FROM DISCIPLINA
    LEFT JOIN PROFESSOR_DISCIPLINA ON DISCIPLINA.codigo_disciplina = PROFESSOR_DISCIPLINA.codigo_disciplina
    LEFT JOIN PROFESSOR ON PROFESSOR_DISCIPLINA.codigo_professor = PROFESSOR.codigo_professor
    WHERE PROFESSOR.codigo_professor IS NULL
);

#4
SELECT COUNT(*) as total_professores
FROM PROFESSOR;

#5
SELECT DISTINCT ALUNO.*
FROM ALUNO
JOIN DISCIPLINA_ALUNO ON ALUNO.codigo_aluno = DISCIPLINA_ALUNO.codigo_aluno
JOIN DISCIPLINA ON DISCIPLINA_ALUNO.codigo_disciplina = DISCIPLINA.codigo_disciplina
WHERE YEAR(DISCIPLINA_ANO) BETWEEN 2000 AND 2020;




